version: "3"

services:
  db:
    container_name: my_sql
    image: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: sa
    volumes:
      - ./db:/var/lib/mysql:rw
    ports:
      - 3307:3307
    restart: always

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: "backend"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/testdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sa
