version: "3"

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    container_name: "frontend"
    networks:
      - mohaeng_network

networks:
  mohaeng_network:
